CREATE DATABASE IF NOT EXISTS projek_uas;
USE projek_uas;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS kategori (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_kategori VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS koleksi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_item VARCHAR(150) NOT NULL,
    deskripsi TEXT,
    tanggal_masuk DATE NOT NULL,
    foto VARCHAR(255),
    kategori_id INT,
    user_id INT,
    FOREIGN KEY (kategori_id) REFERENCES kategori(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

INSERT INTO kategori (nama_kategori) VALUES
('Keluarga'),('Sahabat'),('Sekolah'),('Perjalanan'),('Hadiah'),('Kenangan Mantan');

-- default admin: username 'admin', password 'admin123'
-- password hash generated by PHP password_hash('admin123', PASSWORD_DEFAULT)
INSERT INTO users (username, password) VALUES
('admin', '$2y$10$1bDqDc8jC6aMlzJms6OE6u4jEdHqXKdsxZ09P6u8nWQJgOHayeRJK');
